### ISSUE TITLE
ER20 Bridge reverts with wrong message for withdrawing burnt nonce

### ISSUE THREAD

**Issue by vega-paul** [vegaprotocol/MultisigControl#110]
ERC20 bridge contract returns an unexpected solidity exception when attempt to withdraw an ERC20 token amount after the nonce for the withdrawal has been burned on the  multisig contract.

bridge contract reverts with

'execution reverted: VM Exception while processing transaction: revert nonce already used'

Steps to produce

Deposit erc20 token balance to bridge
set asset limit to threshold and lifetime limit to appropriate values 
Initiate withdrawal on vega by submitted a withdrawSubmission and confirm wallet hash
Get approval details for withdrawal from Vega (includes nonce)
Approve trx on erc20 contract  for amount to withdraw
Burn nonce on multisig (nonce from vega) and confirm receipt and event
Withdraw Asset on bridge using withdraw_asset function and nonce from vega

Actual - bridge contract reverts with  revert nonce already used
Expected - bridge contract reverts to confirm nonce no longer exists

if withdraw_asset used before the withdrawal delay is expired we return
‘revert large withdraw is not old enough’ on a burned nonce whilst we wait for the withdrawal delay to expire

**Comment by vega-paul** [comment]
[yvon_or_justin](https://app.slack.com/team/UBCB7SU4B)  [10 minutes ago](https://vegaprotocol.slack.com/archives/CMVDT0ZU6/p1653908846175819?thread_ts=1653908716.463749&cid=CMVDT0ZU6)
Well, that's the goal of the burn nonce right?





[Paul](https://app.slack.com/team/U0260QRSFPT)  [9 minutes ago](https://vegaprotocol.slack.com/archives/CMVDT0ZU6/p1653908911564279?thread_ts=1653908716.463749&cid=CMVDT0ZU6)
this is only my interpretation as no documentation exists
Attempting to withdraw a token where the nonce was burnt shouldnt return ‘nonce already used’?


[Paul](https://app.slack.com/team/U0260QRSFPT)  [9 minutes ago](https://vegaprotocol.slack.com/archives/CMVDT0ZU6/p1653908918834549?thread_ts=1653908716.463749&cid=CMVDT0ZU6)
Happy to close if thats expected


[Emil Bay](https://app.slack.com/team/U027AM1CWUF)  [7 minutes ago](https://vegaprotocol.slack.com/archives/CMVDT0ZU6/p1653909043891839?thread_ts=1653908716.463749&cid=CMVDT0ZU6)
Sounds like what happened here is expected. You burned the nonce making it unusable, then try to use it and Ethereum reverts


[Paul](https://app.slack.com/team/U0260QRSFPT)  [6 minutes ago](https://vegaprotocol.slack.com/archives/CMVDT0ZU6/p1653909086604629?thread_ts=1653908716.463749&cid=CMVDT0ZU6)
‘nonce already used’ for unusable nonces - its the message which vexes me


[Paul](https://app.slack.com/team/U0260QRSFPT)  [5 minutes ago](https://vegaprotocol.slack.com/archives/CMVDT0ZU6/p1653909138514479?thread_ts=1653908716.463749&cid=CMVDT0ZU6)
Also we get ‘revert large withdraw is not old enough’ on a burned nonce whilst we wait for the withdrawal delay to expire!


[Paul](https://app.slack.com/team/U0260QRSFPT)  [4 minutes ago](https://vegaprotocol.slack.com/archives/CMVDT0ZU6/p1653909205741399?thread_ts=1653908716.463749&cid=CMVDT0ZU6)
Happy to close if this is expected (edited) 


[Emil Bay](https://app.slack.com/team/U027AM1CWUF)  [3 minutes ago](https://vegaprotocol.slack.com/archives/CMVDT0ZU6/p1653909245436509?thread_ts=1653908716.463749&cid=CMVDT0ZU6)
Ah I see, internally the co tract doesn't distinguish what the nonce was used for. Burning is essentially using the nonce for a no-op


[yvon_or_justin](https://app.slack.com/team/UBCB7SU4B)  [2 minutes ago](https://vegaprotocol.slack.com/archives/CMVDT0ZU6/p1653909331962079?thread_ts=1653908716.463749&cid=CMVDT0ZU6)
It is expected


[yvon_or_justin](https://app.slack.com/team/UBCB7SU4B)  [2 minutes ago](https://vegaprotocol.slack.com/archives/CMVDT0ZU6/p1653909343770169?thread_ts=1653908716.463749&cid=CMVDT0ZU6)
We revert like fucks as usual, but the behaviour is correct

**Comment by C0deMunk33** [comment]
the uniqueness of the transaction is tied to the nonce so "nonce already used" seemed appropriate at the time. 

What would you prefer it say? We can make that change if auditors are cool with it.

Also, yeah, the contract doesn't know what the sigs are for, only what contract/method they are made for
