### ISSUE TITLE
Add tests/acceptance criteria labels for 0069-VCBS

### ISSUE THREAD

**Issue by edd** [vegaprotocol/MultisigControl#68]
https://github.com/vegaprotocol/specs/blob/master/protocol/0069-VCBS-validators_chosen_by_stake.md#multisig-update adds some extra requirements on MultisigControl. This task is to ensure that there are tests for the acceptance criteria, and to label them with the codes from the spec so they're picked up by [vegaprotocol/approbation](https://github.com/vegaprotocol/approbation)

**Comment by gordsport** [comment]
Closing this issue as the tests mentioned here should/will be covered by system tests.
- https://github.com/vegaprotocol/system-tests/issues/395
