### ISSUE TITLE
Update ERC20 Bridge Logic contract to allow people to self-allowlist

### ISSUE THREAD

**Issue by gordsport** [vegaprotocol/MultisigControl#76]
As per the spec update in PR:

- https://github.com/vegaprotocol/specs-internal/pull/1044

We require that the deposit limits in the [ERC20 Bridge Logic contract sweetwaterPP branch](https://github.com/vegaprotocol/MultisigControl/tree/sweetwaterPP) to be:

- Any ETH address can add/remove *itself* from the list of exempt addresses.
- Any ETH address on the deposit allowlist can deposit as normal, bypassing deposit limits both on ETH key and destination Vega key.
- Withdrawal limits *are still in place for everyone*. 
- Any ETH address can use a method on the smart contract to add or remove itself (own ETH address) from the exemption list

**Comment by C0deMunk33** [comment]
working on tests now, the changes are in place, it looks like this:
`require(msg.sender == exemption_lister || msg.sender == depositor, "unauthorized exemption lister");`

**Comment by C0deMunk33** [comment]
Tests are in, we should be ready for audit @gordsport 
@najienka if you would like to review this and/or make more tests, that would be awesome.
